.
.TH SHMENU "1" "January 2023" "shmenu" "User Commands"
.SH NAME
shmenu \- :bash-based menu tui

.SH SYNOPSIS
.B shmenu

.SH DESCRIPTION
A bash-based menu tui used to choose options through vi-like keybindings
.PP

.SH USAGE
.
.nf

j: scroll down
k: scroll up
h: select
l: quit

enter: select
q: quit

.
.fi

.SH OPTIONS
.
.nf

-: \-p | \-\-prompt
The menu's prompt/title

-: \-o | \-\-options
list of elements to consider as menu options

-: \-h | \-\-help
view this man page


.
.fi
